### ISSUE TITLE
BERT Server Demo - Fails to create kernel due to invalid NEFF

### ISSUE THREAD

**Issue by keithachorn-intel** [aws/aws-neuron-sdk#70]
I am attempting to replicate the BERT Demo as described here: [Link](https://github.com/aws/aws-neuron-sdk/tree/master/src/examples/tensorflow/bert_demo) .  The system used was inf1.2xlarge (although inf1.24xlarge previously failed with the same error).

After downloading the BERT model, training it (per Appendix 1), and compiling the Saved Model for Neuron, the next step is to launch the BERT Server (bert_server.py).  Up to this point, none of the scripts raised any errors.  However, it should be noted that while the uncompiled Saved Model (ie. bert_classifier_saved_model) contains data files in the variables folder, **the compiled Saved Model (bert-saved-model-neuron, output from bert_model.py) only contains the saved_model.pb file with an empty variables folder.**

When the bert_server.py command is launched using: `python bert_server.py --dir bert-saved-model-neuron --parallel 4` , the following output results and the inferencing does not appear to work from the client end:

> WARNING:tensorflow:From bert_server.py:35: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
> 
> WARNING:tensorflow:
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> For more information, please see:
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
>   * https://github.com/tensorflow/addons
>   * https://github.com/tensorflow/io (for I/O related ops)
> If you depend on functionality not listed there, please file an issue.
> 
> 2020-01-23 00:28:46.542790: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
> 2020-01-23 00:28:46.579727: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000015000 Hz
> 2020-01-23 00:28:46.579834: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560b91b98190 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-01-23 00:28:46.579856: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/contrib/predictor/saved_model_predictor.py:153: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
**> 2020-01-23 00:28:52.779828: E tensorflow/core/framework/op_segment.cc:54] Create kernel failed: Invalid argument: neff is invalid
> 2020-01-23 00:28:52.779890: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: neff is invalid
> 	 [[{{node bert/NeuronOp}}]]
> 2020-01-23 00:28:53.737255: E tensorflow/core/framework/op_segment.cc:54] Create kernel failed: Invalid argument: neff is invalid
> 2020-01-23 00:28:53.737303: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: neff is invalid
> 	 [[{{node bert/NeuronOp}}]]
> 2020-01-23 00:28:54.736447: E tensorflow/core/framework/op_segment.cc:54] Create kernel failed: Invalid argument: neff is invalid
> 2020-01-23 00:28:54.736498: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: neff is invalid
> 	 [[{{node bert/NeuronOp}}]]
> 2020-01-23 00:28:55.740208: E tensorflow/core/framework/op_segment.cc:54] Create kernel failed: Invalid argument: neff is invalid
> 2020-01-23 00:28:55.740256: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: neff is invalid**
> 	 [[{{node bert/NeuronOp}}]]
> E0123 00:28:55.793235256    1950 socket_utils_common_posix.cc:197] check for SO_REUSEPORT: {"created":"@1579739335.793224173","description":"SO_REUSEPORT unavailable on compiling system","file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":165}
> current throughput 0
> input processor is waiting
> input processor is waiting
> input processor is waiting
> input processor is waiting
> current throughput 0
> current throughput 0
> current throughput 0
> current throughput 0

The error sequence repeats the same number of times as NeuronCores specified.

Since the compiled model did not result in a NEFF file, I presume this is generated by bert_server.py on-the-fly.  However, there is currently insufficient documentation to resolve this error, and I do not see it raised elsewhere in this repository.  Help in resolving this error would be much appreciated.

**Comment by keithachorn-intel** [comment]
@spring01 - I applied the code change provided and re-attempted compilation.  The error code resulted after 45+ minutes on a c5.4xlarge instance:
```
Traceback (most recent call last):
  File "bert_model.py", line 246, in <module>
    main()
  File "bert_model.py", line 113, in main
    raise AttributeError('Neuron executable (neff) is empty. Please check neuron-cc is installed and working properly (`pip install neuron-cc` to install neuron-cc).')
AttributeError: Neuron executable (neff) is empty. Please check neuron-cc is installed and working properly (`pip install neuron-cc` to install neuron-cc).
```
So I am now left knowing that the error occurred during compilation rather than when the bert_server.py was launched.  However, there is no indication why the compilation failed.  The input saved model - created using Appendix 1 - appears adequate.  And neuron-cc is properly installed.

Should this require a new issue ticket or is this one sufficient?

**Comment by micwade** [comment]
Hi, keithachorn-intel.

We were able to reproduce and are actively debugging the issue.  Thanks for making us aware of this issue.  We will update back on fix progress.  No need for a new ticket - this one is sufficient.

Mike

**Comment by micwade** [comment]
Hi, keithachorn-intel.

Please update to the latest version of Neuron SDK software.  The latest release has a specific change to address this escape and we’ve plugged the hole with additional testing.  Thanks again for letting us know and please reopen this issue if you find it’s still not working.

Mike

**Comment by yugoren** [comment]
I believe I have the same issue even though I brought up my instance yesterday and ran all the updates today again. I'm working on an `inf1.6xlarge` instance for all steps and I have a working `neuron-cc` installed:
```bash
(aws_neuron_tensorflow_p36) ubuntu@ip-172-31-70-98:~/NeuronSDK/src/examples/tensorflow/bert_demo$ neuron-cc --version
Neuron Compiler version 1.0.4680.0+5844509397

HWM version 1.0.602.0-5843326937
NEFF version 0.6
TVM version 1.0.1219.0+5844423152
NumPy version 1.17.2
MXNet not available
TF version 1.15.0
```
I already have the model stored and running `bert_model.py` results in the following:
```bash
(aws_neuron_tensorflow_p36) ubuntu@ip-172-31-70-98:~/NeuronSDK/src/examples/tensorflow/bert_demo$ python bert_model.py --input_saved_model $BERT_LARGE_SAVED_MODEL --output_saved_model ./bert-saved-model-neuron --crude_gelu
WARNING:tensorflow:From bert_model.py:144: fuse (from tensorflow.python.neuron.python.fuse) is deprecated and will be removed in a future version.
Instructions for updating:
Please refer to AWS documentation on Neuron integrated TensorFlow 2.0.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2020-01-30 22:16:04.706512: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-01-30 22:16:04.728128: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2999995000 Hz
2020-01-30 22:16:04.729283: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5617b1b6e730 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-30 22:16:04.729307: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/contrib/predictor/saved_model_predictor.py:153: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
WARNING:tensorflow:From bert_model.py:32: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From bert_model.py:35: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From bert_model.py:214: The name tf.rsqrt is deprecated. Please use tf.math.rsqrt instead.

WARNING:tensorflow:From bert_model.py:89: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "bert_model.py", line 245, in <module>
    main()
  File "bert_model.py", line 112, in main
    raise AttributeError('Neuron executable (neff) is empty. Please check neuron-cc is installed and working properly (`pip install neuron-cc` to install neuron-cc).')
AttributeError: Neuron executable (neff) is empty. Please check neuron-cc is installed and working properly (`pip install neuron-cc` to install neuron-cc).
```

**Comment by keithachorn-intel** [comment]
@yugoren - If you're using a model you previously compiled, try starting again with the [uncompiled]] Saved Model and re-compile it.  Doing this fixed the issue for me.

**Comment by yugoren** [comment]
@keithachorn-intel I tried re-running the entire exercise from scratch, no changes. One change I did was to modify the fine-tuning part to train only for 0.1 epoch rather than 3 (since it takes unnecessarily long; I just want to test the latency numbers for BERT with `inf1` instance for now), and I think it's a valid change looking at the implementation [here](https://github.com/google-research/bert/blob/master/run_classifier.py#L843-L844).
