### ISSUE TITLE
Upgrade torch-neuron to torch 1.6.0

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-neuron-sdk#212]
Hello, looking [here](https://pip.repos.neuron.amazonaws.com/torch-neuron/) latest version of `torch-neuron` is `torch_neuron-1.5.1.1.0.1978.0-py3-none-linux_x86_64.whl`

Torch `1.6.0` adds some several new functionalities (like `bucketsize`) that causes this issue when using `1.5.0` version

```
AttributeError: module 'torch' has no attribute 'bucketize'
```

is it possibile then to upgrade torch-neuron to support torch 1.6.0?

Thank you.

**Comment by mrnikwaws** [comment]
Hi Loreto,  

You can find the planned release of PyTorch 1.7.0 here: https://github.com/aws/aws-neuron-sdk/projects/2

**Comment by mrnikwaws** [comment]
I am going to close this ticket - please re-open it if you have further questions.

**Comment by loretoparisi** [comment]
@mrnikwaws yes do you have an ETA for the 1.7.0? thank you

**Comment by mrnikwaws** [comment]
Hi Loreto, 

We have been actively working on PyTorch 1.7 and hope to release it soon - since this in the 'Coming soon' we hope to make it available in the next 2-3 weeks.  Please see https://github.com/aws/aws-neuron-sdk/blob/master/roadmap-readme.md for more information on projected timelines for AWS Neuron roadmap items
